[package]
name = "doc-clone"
version = "0.0.2"
edition = "2021"
description = "A utility for duplicating doc comments across files."
license = "MIT"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }

[dev-dependencies]
tempfile = "3.3.0"
